PROGRAM AREAS;
USES CRT;
VAR
A, L : INTEGER;
AREA, PERIMETRO: REAL;
BEGIN
CLRSCR;
WRITE('INGRESA EL VALOR DEL ANCHO DEL RECTANGULO: ');
READ(A);
WRITE('INGRESA EL VALOR DE LA ALTURA DEL RECTANGULO: ');
READ(L);
AREA:= A*L;
PERIMETRO:= 2*(A+L);
WRITELN('');
WRITELN('EL AREA DEL RECTANGULO ES: ',AREA:0:0,' M2');
WRITELN('EL PERIMETRO DEL RECTANGULO ES: ',PERIMETRO:0:0,' M');
READKEY();
END.
