PROGRAM ADICION;
USES CRT;
VAR
A, B : REAL;
SUMA, RESTA, PRODUCTO, DIVISION: REAL;
BEGIN
CLRSCR;
WRITE('INGRESA EL PRIMER NUMERO: ');
READ(A);
WRITE('INGRESA EL SEGUNDO NUMERO: ');
READ(B);
SUMA:= A+B;
RESTA:=A-B;
PRODUCTO:=A*B;
DIVISION:=A/B;
WRITELN('');
WRITELN('LA SUMA DE LOS DOS NUMEROS ES: ',SUMA:0:0);
WRITELN('LA RESTA DE LOS DOS NUMEROS ES: ',RESTA:0:0);
WRITELN('EL PRODUCTO DE LOS DOS NUMEROS ES: ',PRODUCTO:0:0);
WRITELN('LA DIVISION DE LOS DOS NUMEROS ES: ',DIVISION:1:1);
READKEY();
END.
