PROGRAM EXPONENTE;
USES CRT;
VAR
M, N : INTEGER;
POTENCIA , RAIZN : REAL;
BEGIN
CLRSCR;
WRITE('INGRESE LA BASE: ');
READ(M);
WRITE('INGRESE EL EXPONENTE: ');
READ(N);
POTENCIA:=EXP(N*LN(M));
RAIZN:=EXP((1/N)*LN(M));
WRITELN('');
WRITELN('LA POTENCIA ES: ',POTENCIA:1:1);
WRITELN('LA RAIZ ES: ',RAIZN:1:1);
READKEY();
END.