PROGRAM ADICION;
USES CRT;
VAR
A, B : REAL;
SUMA: REAL;
BEGIN
CLRSCR;
WRITE('INGRESA EL PRIMER NUMERO: ');
READ(A);
WRITE('INGRESA EL SEGUNDO NUMERO: ');
READ(B);
SUMA:= A+B;
WRITE('LA SUMA DE LOS DOS NUMEROS ES: ',SUMA:0:0);
READKEY();
END.
