PROGRAM RAIZCUADRADA;
USES CRT;
VAR
A: INTEGER;
R: REAL;
BEGIN
CLRSCR;
WRITE('INGRESA EL NUMERO: ');
READ(A);
IF A > 0 THEN
BEGIN
R:=SQRT(A);
WRITE('LA RAIZ ES: ',R:1:1);
END
ELSE
BEGIN
WRITELN('EL NUMERO INGRESADO ES MENOR QUE CERO (NEGATIVO)..');
WRITELN('NO SE PUEDE CALCULAR LA RAIZ DE UN NUMERO NEGATIVO');
END;
READKEY();
END.