PROGRAM ARITMETICA;
USES CRT;
VAR
A, B, C : INTEGER;
SUMA, PRODUCTO : REAL;
BEGIN
CLRSCR;
WRITELN('INGRESE LOS TRES NUMEROS: ');
READLN(A);
READLN(B);
READLN(C);
SUMA:=A+B+C;
PRODUCTO:=A*B*C;
WRITELN('LA SUMA ES: ', SUMA:0:0);
WRITELN('EL PRODUCTO ES: ',PRODUCTO:0:0);
READKEY();
END.