PROGRAM CAMBIO;
USES CRT;
VAR
SOLES: REAL;
DOLARES: REAL;
BEGIN
CLRSCR;
WRITELN(' PROGRAMA QUE CAMBIA SOLES A DOLARES (TIPO DE CAMBIO: 3.96)');
WRITELN('');
WRITE(' INGRESE LA CANTIDAD DE SOLES: ');
READ(SOLES);
WRITELN('');
IF SOLES>5000 THEN
BEGIN
WRITELN(' NO SE CUENTA CON DICHA CANTIDAD :(');
END
ELSE
BEGIN
DOLARES:=SOLES/3.96;
WRITELN(' S/', SOLES:0:2, ' EQUIVALE A $', DOLARES:0:2);
END;
READKEY();
END.
