PROGRAM PARIDAD;
USES CRT;
VAR
A: INTEGER;
BEGIN
CLRSCR;
WRITELN(' ESTUDIANTE: Tumbalobos Peralta, Cristopher R.');
WRITELN(' PROGRAMA QUE IDENTIFICA SI UN NUMERO ES PAR O IMPAR');
WRITELN('');
WRITE(' INGRESA UN NUMERO: ');
READ(A);
WRITELN('');
IF (A MOD 2)=0 THEN
BEGIN
WRITELN(' EL NUMERO ES PAR');
END
ELSE
BEGIN
WRITELN(' EL NUMERO ES IMPAR');
END;
READKEY();
END.
