PROGRAM PROGRESION;
USES CRT;
VAR
A1, N, R :  INTEGER;
TN : REAL;
BEGIN
CLRSCR;
WRITELN(' ESTUDIANTE: Tumbalobos Peralta, Cristopher R.');
WRITELN(' PROGRAMA QUE CALCULA EL TERMINO ENESIMO DE UNA PROGRESION');
WRITELN('');
WRITE(' INGRESE EL NUMERO DE TERMINOS QUE QUIERE CALCULAR: ');
READ(N);
WRITE(' INGRESE EL PRIMER TERMINO DE LA PROGRESION: ');
READ(A1);
WRITE(' INGRESE LA RAZON DE LA PROGRESION ARITMETICA: ');
READ(R);
TN:=A1+(N-1)*R;
WRITELN('');
WRITELN(' EL TERMINO BUSCADO ES: ',TN:0:0);
READKEY();
END.
